# Generated by Django 6.0.3 on 2026-04-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_owner_unlockotp_deviceaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='security_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
