# Generated by Django 6.0.3 on 2026-04-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical'), ('success', 'Success')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='alert_snapshots/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(default='Locker Alert', max_length=150),
        ),
    ]
