# Generated by Django 6.0.3 on 2026-04-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safeevent',
            name='event_type',
            field=models.CharField(choices=[('FACE_OK', 'Authorized Face'), ('FACE_UNKNOWN', 'Unknown Face'), ('PASSCODE_OK', 'Passcode Accepted'), ('PASSCODE_FAIL', 'Passcode Rejected'), ('SAFE_OPENED', 'Safe Opened'), ('SAFE_CLOSED', 'Safe Closed'), ('FORCED_ENTRY', 'Forced Entry Detected')], max_length=20),
        ),
    ]
