# Generated by Django 6.0.3 on 2026-04-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_last_seen_device_security_token'),
        ('events', '0002_alter_safeevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_status', models.CharField(choices=[('granted', 'Access Granted'), ('denied', 'Access Denied')], max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='access_logs/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs_entry', to='devices.device')),
            ],
        ),
    ]
